# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "docDock Plus"
license = "MIT"
licenselink = "https://github.com/laakmann/hugo-theme-docdock-plus/blob/master/LICENSE.md"
description = "Nested navigation, blogging, and more"
homepage = "https://github.com/laakmann/hugo-theme-dockdock-plus"
repo = "https://github.com/laakmann/hugo-theme-dockdock-plus"
tags = ["documentation", "blog","menu","slide","search"]
features = ["documentation","blog","menu","nested sections","search","slide", "attachments"]
min_version = 0.25

[author]
  name = "Peter Laakmann"
  homepage = "http://empiricalscrutiny.com/"

[original]
  name = "docDock"
  homepage = "https://github.com/vjeantet/hugo-theme-docdock"
  repo = "https://github.com/vjeantet/hugo-theme-docdock"
  licenselink = "https://github.com/vjeantet/hugo-theme-docdock/blob/master/LICENSE.md"